#!/bin/python3

from random import choice
from time import sleep

print("Ask the Universe your question as we shuffle the cards...")
sleep(5)

replies = ['Your card is, The Fool',
        'Your card is, The Magician',
        'Your card is, The High Priestess',
        'Your card is, The Empress',
        'Your card is, The Emperor',
        'you pulled the card, The Hierophant',
        'Your card is, The Lovers',
        'Your card is, The Chariot',
        'Your card is, Strength',
        'You chose, The Hermit card',
        'Your card is, The Wheel of Fortune',
        'Your card is, Justice',
        'Your card is, The Hanged Man',
        'You pulled the Death card',
        'you pulled the card, Temperance',
        'you pulled the card, The Devil',
        'You chose, The Tower',
        'You chose, The Star',
        'You chose, The Moon',
        'You chose, The Sun',
        'You chose, Judgement',
        'You chose, The World',
        'You drew the Ace of Wands',
        'You drew the Two of Wands',
        'You drew the Three of Wands',
        'You drew the Four of Wands',
        'You drew the Five of Wands',
        'You drew the Six of Wands',
        'You drew the Seven of Wands',
        'You drew the Eight of Wands',
        'You drew the Nine of Wands',
        'You drew the Ten of Wands',
        'You drew the Page of Wands',
        'You drew the Knight of Wands',
        'You drew the Queen of Wands',
        'You drew the King of Wands',
        'You drew the Ace of Cups',
        'You drew the Two of Cups',
        'You drew the Three of Cups',
        'You drew the Four of Cups',
        'You drew the Five of Cups',
        'You drew the Six of Cups',
        'You drew the Seven of Cups',
        'You drew the Eight of Cups',
        'You drew the Nine of Cups',
        'You drew the Ten of Cups',
        'You drew the Page of Cups',
        'You drew the Knight of Cups',
        'You drew the Queen of Cups',
        'You drew the King of Cups',
        'You drew the Ace of Swords',
        'You drew the Two of Swords',
        'You drew the Three of Swords',
        'You drew the Four of Swords',
        'You drew the Five of Swords',
        'You drew the Six of Swords',
        'You drew the Seven of Swords',
        'You drew the Eight of Swords',
        'You drew the Nine of Swords',
        'You drew the Ten of Swords',
        'You drew the Page of Swords',
        'You drew the Knight of Swords',
        'You drew the Queen of Swords',
        'You drew the King of Swords',
        'You drew the Ace of Coins',
        'You drew the Two of Coins',
        'You drew the Three of Coins',
        'You drew the Four of Coins',
        'You drew the Five of Coins',
        'You drew the Six of Coins',
        'You drew the Seven of Coins',
        'You drew the Eight of Coins',
        'You drew the Nine of Coins',
        'You drew the Ten of Coins',
        'You drew the Page of Coins',
        'You drew the Knight of Coins',
        'You drew the Queen of Coins',
        'You drew the King of Coins']

print(choice(replies))
